### PR TITLE
include automatic_retries check before retrying

### PR DESCRIPTION
**Pull request by guyisra**
It seems nothing in the chain output-http -> mixin -> manticore -> apache http client check to stop retries with the automatic_retries config, so retries continue endlessly

### CODE REVIEW

**Comment by andrewvc** [comment]
We actually do set that in the mixin: https://github.com/logstash-plugins/logstash-mixin-http_client/blob/master/lib/logstash/plugin_mixins/http_client.rb#L110

This is a confusing setting however, because the HTTP output also has its own option, `retry_failed`. I think we should find a way to unify these two.

It's a bit tricky because `retry_failed` retries all requests, while `automatic_retries` only retries idempotent ones. Whatever the fix is, it will be a breaking change.

One problem with automatic retries is that it doesn't have any concept of an exponential backoff. My feeling is we should find a way to omit that option from this plugin and handle all retry logic manually inside.

Thoughts @guyisra ?

**Comment by guyisra** [comment]
@andrewvc I think the main culprit is exposing parameters from different layers (plugin, http_client, manticore) and some times there are duplications and confusions, like this one.

As I see it, retry_failed should be the on/off switch and automatic_retries should be the number of retries. There shouldn't be overlap in functionality (like setting retry_failed to true and automatic_retries to 0, or retry_failed false and automatic_retries to some number)

As you said, the overlap is what causing the confusion. I think we should hide the logic from the external API of the plugin, and provide only functionality

**Comment by andrewvc** [comment]
I agree with that sentiment. Unfortunately this will be a breaking change.
I think we should also modify the mixin to no longer expose automatic
retries as a direct option.

**Comment by kares** [comment]
this has gotten stale, the [client is no longer sending async requests](https://github.com/logstash-plugins/logstash-output-http/blob/v5.3.0/lib/logstash/outputs/http.rb#L240=)

**Pull request closed without merging**
