### PR TITLE
Migrate to Manticore

### PR DESCRIPTION
**Pull request by jakozaur**
Several improvements:
1. Migrate to Manticore.
a) fixes SSL issues
b) much better performance, thanks to connection pools
2. Respect `verify_ssl` configuration.
3. Allow many concurrent respects.
a) Serial round-trip between USA and Europe can kill your day.
b) With multiple concurrent requests, latency is not longer an issue.
c) I'm Ruby noob. It still can be done so much nicer in Java/Scala, but don't know how to do it here.

To give some stats: perf in my quick benchmark grown from 50 -> 2700 lines / second.

### CODE REVIEW

**Comment by jakozaur** [comment]
@ph please review :smile:

**Comment by suyograo** [comment]
+1 for manticore. @andrewvc i know you were attempting to do this at some point. Review please

**Comment by andrewvc** [comment]
@jakozaur this looks great!  I really loved your approach using async vs. sync requests here!

I've submitted these patches as part of a larger PR after performing some refactors in #19 I hope you don't mind, but we're trying to switch to using the HttpClient mixin in official LS plugins vs. the raw manticore client.

Also, would you mind signing the CLA for your patch? https://www.elastic.co/contributor-agreement We'll need that to merge your commits in :)

BTW, if you could review #19 that would be much appreciated!

**Comment by jakozaur** [comment]
Signed CLA.

**Comment by andrewvc** [comment]
@jakozaur awesome! I'm going to close this issue since your commits are in #19 and we'll be merging that one instead

**Pull request closed without merging**
