### PR TITLE
Adding support for disabling SSL certificate validation.

### PR DESCRIPTION
**Pull request by jessegonzalez**
Dependent on jordansissel/ruby-ftw#32.

### CODE REVIEW

**Comment by jordansissel** [comment]
FYI, this branch in progress: https://github.com/logstash-plugins/logstash-output-http/compare/feature/ssl-configuration - it includes disabling SSL certificate verification (Despite doing so being a _very_ bad idea)

**Comment by Stono** [comment]
+1 for this merge request, please accept it and pull in as its causing a massive headache.

**Comment by jordansissel** [comment]
@Stono Sorry for any frustrations in delays. You are able to take this patch and merge it into your systems without any action from me. You can fetch the patch with `wget https://github.com/logstash-plugins/logstash-output-http/pull/12.patch` and apply it locally if it is urgent for you.

**Comment by Stono** [comment]
Yeah that's precisely what I've done I'd just rather not have to be applying patches as part of my server builds :D

I also found out why my CA wasn't being accepted, see https://github.com/jordansissel/ruby-ftw/pull/33

**Comment by suyograo** [comment]
Closing this as @andrewvc fixed this in #19

**Pull request closed without merging**
